# start index from 1 and not from 0
set -g base-index 1

# vi/nvim-like copy mode
setw -g mode-keys vi

# reload conf
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# pan navigation (in place of ctrl+b+arrow)
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# visual/yank
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-v send -X rectangle-toggle

# line motions
bind-key -T copy-mode-vi 0 send -X start-of-line
bind-key -T copy-mode-vi ^ send -X back-to-indentation
bind-key -T copy-mode-vi '$' send -X end-of-line

# file/buffer motions
bind-key -T copy-mode-vi g send -X top-line
bind-key -T copy-mode-vi G send -X bottom-line

# search
bind-key -T copy-mode-vi / send -X search-forward
bind-key -T copy-mode-vi ? send -X search-backward
bind-key -T copy-mode-vi n send -X search-again
bind-key -T copy-mode-vi N send -X search-reverse

