wallpaper {
    monitor = DP-5
    path = /home/a2n/Nextcloud/photos/wallpaper/best/Screenshot_20260608_134358.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = /home/a2n/Nextcloud/photos/wallpaper/best/Screenshot_20260608_134358.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/a2n/Nextcloud/photos/wallpaper/best/Screenshot_20260608_134358.png
    fit_mode = cover
}

# remove the text put by hyprland on the wallpaper
splash = false
